### ISSUE TITLE
Namespace change

### ISSUE THREAD

**Issue by yagnasrinath** [smallk/smallk.github.io#1]
namespace elem is not available. Everywhere i had to use 'El' as namespace instead of the one 'elem'. Also there is no header file called elemental.hpp, its El.hpp. I do not know whether its the change in latest version of elemental. I am using elemental 0.84

**Comment by bldrake** [comment]
You are not using version 0.84 apparently. Just checked our latest version 0.84-p1. There is still elemental.hpp and the namespace is elem. 

El.hpp and the El namespace is used for version 0.85, which includes sparse matrix code and hooks into Python and Octave. You should make sure you have 
the latest STABLE release which is 0.84-p1. 

Barry 

----- Original Message -----
